language: node_js
node_js:
  - lts/*
script:
  - npm run build
  - npm run check
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: dist
